### PR TITLE
Apple bme

### PR DESCRIPTION
**Pull request by mazepeda**

### CODE REVIEW

**Review by FFAxKenny — CHANGES_REQUESTED** [review]
looks like the .pio directory was added by accident

**Review by aobatake — COMMENTED** [review]
I also think your .vscode directory was added by accident. If those are user specific files, make sure to add those directories into the .gitignore.

**Comment by FFAxKenny** [comment]
Hello - I noticed this got closed. You don't have to close the PR if you're just adding changes, you can just push to the branch and the changes will show up in the PR. That way, any discussion is captured in one place 😄

**Comment by mazepeda** [comment]
Ok, sorry about the confusion. This is my first PR, so I’m not really sure
what the whole process is. I'm actually not even sure if I've been cloning
the repository the right way. I've been using the GitHub Desktop app so far
to do all these changes.

I start by opening the GitHut Desktop app. I started by choosing 'clone a
repository from the internet', finding the 'scel-hawaii/control-tower'
repository that I have linked to my GitHub account and clicking clone. From
here, I use the 'Open in Visual Studio Code' button next to the section
that says 'Open the repository in your external editor'.

Once Visual Studio opens, I click on the little dropdown menu on the bottom
left to switch from the master branch to the apple_bme branch that I was
working in and made the changes to the apple sensor code. This is when I
went to the .gitignore file in the weatherbox_firmware folder and added in
.pio and .vscode because you said that those are local files created that
we don't want stored with the original code because they're specific to me
and my computer, correct?

Kenny, you also said that even though I added those two instructions to the
.gitignore file, I still need to run the *git rm* command to remove those
files since they were already saved to branch in a previous pull request I
made?

 After I run the* git rm* command for both .pio and .vscode, I can click
the Pull Request dropdown menu on the bottom of the window in Visual
Studio, comment on the changes I made, and then click 'Comment' to edit the
previous pull request I made with these new changes without closing the old
request so that we have all the comments still recorded, correct?

Sorry if these seem like they're pretty obvious or simple things, I just
was never really shown the correct way to do this and I'm trying to make
new documentation to give a very simplified explanation of how to do things
for new members in the future.

Thank you,
Mike

**Pull request closed without merging**
